name: Caps2Ctrl Release

# on: push
on:
  push:
    tags:
      - 'v*'
jobs:
  Example2:
    name: Caps2Ctrl
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ahk2Exe
        uses: nekocodeX/GitHub-Action-Ahk2Exe@main
        with:
          in: caps2ctrl.ahk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: caps2ctrl.exe
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
